# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "builder"
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  # Set the guest time to match the host.
  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/New_York /etc/localtime", run: "always"

  # vagrant requires a static IP when using NFS.
  # Change the ip to an available address.
  config.vm.network "private_network", ip: "192.168.56.10", name: "vboxnet0"

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.synced_folder "/Users/shague/git", "/git", type: "nfs", mount_options: ['nolock']
  config.vm.synced_folder "/opt/projects", "/projects", type: "nfs", mount_options: ['nolock', 'ro']

  config.vm.provision "file", source: ".bashrc", destination: ".bashrc"
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  config.vm.provision "file", source: "~/.gitignore", destination: ".gitignore"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: ".ssh/id_rsa"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "builder"
  end

  #if Vagrant.has_plugin?("vagrant-vbguest")
  #  config.vbguest.auto_update = true
  #end
end

# Set vagrant to not create its own vboxnet0.
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end
